make: ford,hyundai,kia,maruthi
automobile:
  make:
    - hyundai
    - kia
    - Chevrolet
    - Datsun
    - Fiat
    - Ford
    - Honda
    - Isuzu
    - Jeep
    - Mahindra
    - Maruti Suzuki
    - MG Motors
    - Mitsubishi
    - Nissan
    - Renault
    - Skoda
    - Ssangyong
    - Tata
    - Toyata
    - Volkswagen
  models:
   hyundai:
    - verna
    - creta
   kia:
    - seltos
    - sonet
debug: false
logging:
  console:
    level: DEBUG
spring:
  data:
    mongodb:
      uri: ${DATA_SOURCE}

jwt:
  secret: ${JWT_SECRET}
  expiry: 123456


