make: ford,hyundai,kia,maruthi
automobile:
  make:
    - hyundai
    - kia
    - Chevrolet
    - Datsun
    - Fiat
    - Ford
    - Honda
    - Isuzu
    - Jeep
    - Mahindra
    - Maruti Suzuki
    - MG Motors
    - Mitsubishi
    - Nissan
    - Renault
    - Skoda
    - Ssangyong
    - Tata
    - Toyata
    - Volkswagen
  models:
   hyundai:
    - verna
    - creta
   kia:
    - seltos
    - sonet
debug: true
logging:
  console:
    level: DEBUG